wezterm cli: --workspace requires --new-window
so have the arg parser raise an error if used without it:

```
; wezterm cli spawn --workspace foo
error: The following required arguments were not provided:
    --new-window

USAGE:
    wezterm cli spawn --new-window --workspace <WORKSPACE>

For more information try --help
```

refs: https://github.com/wez/wezterm/issues/2248#issuecomment-1192119746